name: Sync changes scheduled from CE to EE
on:
    workflow_dispatch:
    schedule:
        - cron: "30 21 * * *"

jobs:
    sync-branches:
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-sync-changes.yaml@v1.0.0
        if: github.repository == 'pimcore/admin-ui-classic-bundle'
        strategy:
            fail-fast: false
            matrix:
                ref:
                    [
                        { "base": "1.x", "destination": "1.x" },
                        { "base": "1.6", "destination": "1.6" },
                    ]
        with:
            base_ref: ${{ matrix.ref.base }}
            ref_name: ${{ matrix.ref.destination }}
            target_repo: "ee-admin-ui-classic-bundle"
            auto_merge: true
        secrets:
            SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
            GIT_NAME: ${{ secrets.GIT_NAME }}
            GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
